# Generated by Django 2.2 on 2019-08-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190814_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
