# Generated by Django 2.2 on 2019-08-15 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Author'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Classification'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='items/book.jpg', upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Language'),
        ),
        migrations.AlterField(
            model_name='item',
            name='publish_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PublishHouse'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-text'),
        ),
    ]
